# Generated by Django 5.2.6 on 2026-02-14 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_taskdetails_stdid_taskdetails_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetails',
            name='assingeTo',
        ),
        migrations.AlterField(
            model_name='taskdetails',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='task.task'),
        ),
    ]
