# Generated by Django 5.2.6 on 2025-11-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_employess_task_assignto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignTo',
            field=models.ManyToManyField(related_name='employeeTask', to='task.employess'),
        ),
    ]
